name: Release to NuGet

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
    - name: Get latest release
      id: release
      uses: thebritican/fetch-latest-release@v1.0.3
      with:
        github_token: ${{ secrets.GITHUB>TOKEN }}
    
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore ./Source/Cryptlex.Net/Cryptlex.Net.csproj
      
    - name: Build
      run: dotnet build --no-restore --configuration Release ./Source/Cryptlex.Net/Cryptlex.Net.csproj
      
    - name: Pack nugets
      run: dotnet pack --output ./nupkgs --no-build --no-restore --configuration Release ./Source/Cryptlex.Net/Cryptlex.Net.csproj -p:PackageVersion=${{ steps.latest.outputs.tag_name }}
      
    - name: Push to NuGet
      run: dotnet nuget push "./nupkgs/*.nupkg" --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
